//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OscarHuntService.com.ustyylit.tuservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TUServiceSoap", Namespace="http://tempuri.org/")]
    public partial class TUService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendOrderUnencryptedOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReceiveOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAesStrOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccessTokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetErrorCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeAesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrderInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStockOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TUService() {
            this.Url = global::OscarHuntService.Properties.Settings.Default.OscarHuntService_com_ustyylit_tuservice_TUService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendOrderUnencryptedCompletedEventHandler SendOrderUnencryptedCompleted;
        
        /// <remarks/>
        public event ReceiveOrderCompletedEventHandler ReceiveOrderCompleted;
        
        /// <remarks/>
        public event GetAesStrCompletedEventHandler GetAesStrCompleted;
        
        /// <remarks/>
        public event GetAccessTokenCompletedEventHandler GetAccessTokenCompleted;
        
        /// <remarks/>
        public event GetErrorCodeCompletedEventHandler GetErrorCodeCompleted;
        
        /// <remarks/>
        public event GetDeAesCompletedEventHandler GetDeAesCompleted;
        
        /// <remarks/>
        public event GetOrderInfoCompletedEventHandler GetOrderInfoCompleted;
        
        /// <remarks/>
        public event GetStockCompletedEventHandler GetStockCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendOrderUnencrypted", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SendOrderUnencrypted(string orders, string AccessToken, string appsecrets, string Brand) {
            object[] results = this.Invoke("SendOrderUnencrypted", new object[] {
                        orders,
                        AccessToken,
                        appsecrets,
                        Brand});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOrderUnencryptedAsync(string orders, string AccessToken, string appsecrets, string Brand) {
            this.SendOrderUnencryptedAsync(orders, AccessToken, appsecrets, Brand, null);
        }
        
        /// <remarks/>
        public void SendOrderUnencryptedAsync(string orders, string AccessToken, string appsecrets, string Brand, object userState) {
            if ((this.SendOrderUnencryptedOperationCompleted == null)) {
                this.SendOrderUnencryptedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOrderUnencryptedOperationCompleted);
            }
            this.InvokeAsync("SendOrderUnencrypted", new object[] {
                        orders,
                        AccessToken,
                        appsecrets,
                        Brand}, this.SendOrderUnencryptedOperationCompleted, userState);
        }
        
        private void OnSendOrderUnencryptedOperationCompleted(object arg) {
            if ((this.SendOrderUnencryptedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOrderUnencryptedCompleted(this, new SendOrderUnencryptedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ReceiveOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReceiveOrder(string orders, string AccessToken, string Brand) {
            object[] results = this.Invoke("ReceiveOrder", new object[] {
                        orders,
                        AccessToken,
                        Brand});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReceiveOrderAsync(string orders, string AccessToken, string Brand) {
            this.ReceiveOrderAsync(orders, AccessToken, Brand, null);
        }
        
        /// <remarks/>
        public void ReceiveOrderAsync(string orders, string AccessToken, string Brand, object userState) {
            if ((this.ReceiveOrderOperationCompleted == null)) {
                this.ReceiveOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceiveOrderOperationCompleted);
            }
            this.InvokeAsync("ReceiveOrder", new object[] {
                        orders,
                        AccessToken,
                        Brand}, this.ReceiveOrderOperationCompleted, userState);
        }
        
        private void OnReceiveOrderOperationCompleted(object arg) {
            if ((this.ReceiveOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReceiveOrderCompleted(this, new ReceiveOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAesStr", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAesStr(string orders, string appsecret, string AccessToken) {
            object[] results = this.Invoke("GetAesStr", new object[] {
                        orders,
                        appsecret,
                        AccessToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAesStrAsync(string orders, string appsecret, string AccessToken) {
            this.GetAesStrAsync(orders, appsecret, AccessToken, null);
        }
        
        /// <remarks/>
        public void GetAesStrAsync(string orders, string appsecret, string AccessToken, object userState) {
            if ((this.GetAesStrOperationCompleted == null)) {
                this.GetAesStrOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAesStrOperationCompleted);
            }
            this.InvokeAsync("GetAesStr", new object[] {
                        orders,
                        appsecret,
                        AccessToken}, this.GetAesStrOperationCompleted, userState);
        }
        
        private void OnGetAesStrOperationCompleted(object arg) {
            if ((this.GetAesStrCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAesStrCompleted(this, new GetAesStrCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAccessToken", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccessToken() {
            object[] results = this.Invoke("GetAccessToken", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccessTokenAsync() {
            this.GetAccessTokenAsync(null);
        }
        
        /// <remarks/>
        public void GetAccessTokenAsync(object userState) {
            if ((this.GetAccessTokenOperationCompleted == null)) {
                this.GetAccessTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccessTokenOperationCompleted);
            }
            this.InvokeAsync("GetAccessToken", new object[0], this.GetAccessTokenOperationCompleted, userState);
        }
        
        private void OnGetAccessTokenOperationCompleted(object arg) {
            if ((this.GetAccessTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccessTokenCompleted(this, new GetAccessTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetErrorCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetErrorCode() {
            object[] results = this.Invoke("GetErrorCode", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetErrorCodeAsync() {
            this.GetErrorCodeAsync(null);
        }
        
        /// <remarks/>
        public void GetErrorCodeAsync(object userState) {
            if ((this.GetErrorCodeOperationCompleted == null)) {
                this.GetErrorCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetErrorCodeOperationCompleted);
            }
            this.InvokeAsync("GetErrorCode", new object[0], this.GetErrorCodeOperationCompleted, userState);
        }
        
        private void OnGetErrorCodeOperationCompleted(object arg) {
            if ((this.GetErrorCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetErrorCodeCompleted(this, new GetErrorCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDeAes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDeAes(string orders, string AccessToken) {
            object[] results = this.Invoke("GetDeAes", new object[] {
                        orders,
                        AccessToken});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeAesAsync(string orders, string AccessToken) {
            this.GetDeAesAsync(orders, AccessToken, null);
        }
        
        /// <remarks/>
        public void GetDeAesAsync(string orders, string AccessToken, object userState) {
            if ((this.GetDeAesOperationCompleted == null)) {
                this.GetDeAesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeAesOperationCompleted);
            }
            this.InvokeAsync("GetDeAes", new object[] {
                        orders,
                        AccessToken}, this.GetDeAesOperationCompleted, userState);
        }
        
        private void OnGetDeAesOperationCompleted(object arg) {
            if ((this.GetDeAesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeAesCompleted(this, new GetDeAesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetOrderInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetOrderInfo(string orders, string appsecrets) {
            object[] results = this.Invoke("GetOrderInfo", new object[] {
                        orders,
                        appsecrets});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetOrderInfoAsync(string orders, string appsecrets) {
            this.GetOrderInfoAsync(orders, appsecrets, null);
        }
        
        /// <remarks/>
        public void GetOrderInfoAsync(string orders, string appsecrets, object userState) {
            if ((this.GetOrderInfoOperationCompleted == null)) {
                this.GetOrderInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrderInfoOperationCompleted);
            }
            this.InvokeAsync("GetOrderInfo", new object[] {
                        orders,
                        appsecrets}, this.GetOrderInfoOperationCompleted, userState);
        }
        
        private void OnGetOrderInfoOperationCompleted(object arg) {
            if ((this.GetOrderInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrderInfoCompleted(this, new GetOrderInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStock", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStock(string AccessToken, string appsecret) {
            object[] results = this.Invoke("GetStock", new object[] {
                        AccessToken,
                        appsecret});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStockAsync(string AccessToken, string appsecret) {
            this.GetStockAsync(AccessToken, appsecret, null);
        }
        
        /// <remarks/>
        public void GetStockAsync(string AccessToken, string appsecret, object userState) {
            if ((this.GetStockOperationCompleted == null)) {
                this.GetStockOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStockOperationCompleted);
            }
            this.InvokeAsync("GetStock", new object[] {
                        AccessToken,
                        appsecret}, this.GetStockOperationCompleted, userState);
        }
        
        private void OnGetStockOperationCompleted(object arg) {
            if ((this.GetStockCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStockCompleted(this, new GetStockCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SendOrderUnencryptedCompletedEventHandler(object sender, SendOrderUnencryptedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOrderUnencryptedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOrderUnencryptedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void ReceiveOrderCompletedEventHandler(object sender, ReceiveOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReceiveOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReceiveOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAesStrCompletedEventHandler(object sender, GetAesStrCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAesStrCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAesStrCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAccessTokenCompletedEventHandler(object sender, GetAccessTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccessTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccessTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetErrorCodeCompletedEventHandler(object sender, GetErrorCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetErrorCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetErrorCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetDeAesCompletedEventHandler(object sender, GetDeAesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeAesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeAesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetOrderInfoCompletedEventHandler(object sender, GetOrderInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrderInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrderInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetStockCompletedEventHandler(object sender, GetStockCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStockCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStockCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591